name: Build and Deploy
on: [push]
jobs:
  build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v1

- name: Use Node.js 10.14.1
  uses: actions/setup-node@v1
  with:
    node-version: 10.14.1
- name: Installing dependencies
  run: npm install
  
- name: Building the Application
  run: npm run build

- name: Upload to S3
  uses: jakejarvis/s3-sync-action@v0.5.0
  with:
    args: --delete
  env:
    AWS_S3_BUCKET: store-ui.alchersan.com
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'eu-west-1'
    SOURCE_DIR: 'build'